### ISSUE TITLE
Research security, reliability and performance issues for developing distributed applications

### ISSUE THREAD

**Issue by wopian** [wopian/hibari-api#1]
### Milestone Brief

Concisely report on the range of technologies, architectures and/or protocols that may provide solutions for developing distributed applications. Be critical of these: what are their merits and limitations? Do security/reliability/performance issues relate to any/all of these? 

**5 Marks**

### Tasks

- [x] Research security impacts
- [x] Research reliability impacts
- [x] Research performance impacts
- [x] Added to report
