### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by wopian** [wopian/hibari-api#12]
### Requirements

Table for each type of data to be stored in the SQLite3 database

### Tasks

- [x] Create a database schema
- [x] Create an empty database with required tables
- [x] Create a database seed for spec testing
- [x] Save data to database
	- [x] users
	- [x] anime
	- [x] library entries
