### ISSUE TITLE
Research merits and limitations of solutions for developing distributed applications

### ISSUE THREAD

**Issue by wopian** [wopian/hibari-api#16]
### Milestone Brief

Concisely report on the range of technologies, architectures and/or protocols that may provide solutions for developing distributed applications. Be critical of these: what are their merits and limitations? Do security/reliability/performance issues relate to any/all of these? 

**5 Marks**

### Tasks

- [x] Research merits of technologies
- [x] Research merits of architectures
- [x] Research merits of protocols
- [x] Research limitations of technologies
- [x] Research limitations of architectures
- [x] Research limitations of protocols
- [x] Added to report
