### ISSUE TITLE
Plan and report how the project will be managed

### ISSUE THREAD

**Issue by wopian** [wopian/hibari-api#7]
### Milestone Brief

Describe the project management processes, roles and responsibilities of group members. You will be required to use a web-based repository for distributed version control and the source code management (SCM) of your Web Services and associated code. Describe this service and the group processes/responsibilities for this. You will also need to provide evidence of you collaborative activity. Plan and report how you intend to do this (e.g. individual and group logs/blogs of communications and meetings, the use of social media).

**15 marks**

### Tasks

- [x] Plan how I intend to do the project management
- [x] Report how I did the project management
- [x] Added to report
